trigger:
  batch: true
  branches:
    include:
    - master
    #- develop
    - releases/*
    - support/*
    - hotfix/*

queue:
  name: devinf

variables:
  - group: "PFDev KeyVault Variables"
  - group: "PowerFarming.Build Variables"

steps:
- task: PowerShell@2
  displayName: Pre initialization
  inputs:
      filePath: ./pre.ps1
      pwsh: true
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      # May possibly need these?
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)

- task: NuGetCommand@2
  displayName: 'Authenticate with NuGet feed'
  inputs:
    command: custom
    arguments: sources update -Name "PowerFarming Nuget" -Source "$(LocalNugetServerUrl)" -Username "$(LocalNugetUserName)" -Password "$(LocalNugetPassword)" -ConfigFile NuGet.Config -StorePasswordInClearText 

# Need prerequisites to use dotnet core first...
#- powershell: dotnet-cake setup.cake --target="Init" --Verbosity=verbose
- task: PowerShell@2
  displayName: Initialization
  inputs:
      filePath: './build.dntool.ps1'
      arguments: '-target "Init" -Verbose'
      pwsh: true
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)
      CAKE_NUGET_USEINPROCESSCLIENT: false
      CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
      # Gitversion to build props
      JENKINS_HOME: "~/"

- task: PowerShell@2
  displayName: Build
  inputs:
      filePath: './build.dntool.ps1'
      arguments: '-target "Build" -Verbose'
      pwsh: true
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
      CAKE_NUGET_USEINPROCESSCLIENT: false
      CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
      # Gitversion to build props
      JENKINS_HOME: "~/"

- powershell: .\build.dntool.ps1 -target "Test"
  displayName: Test
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
      CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
  enabled: false

- powershell: .\build.dntool.ps1 -target "Package"
  displayName: Package
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
      CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true

- powershell: .\build.dntool.ps1 -target "Publish"
  displayName: Publish
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
      CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true

  enabled: false

