trigger:
- develop
- master
- release/*
- hotfix/*

pr:
- develop

queue:
  name: Default

variables:
  - group: "PFDev KeyVault Variables"
  - group: "PowerFarming.Build Variables"

steps:
- checkout: self
  clean: true
  submodules: true
  persistCredentials: true

- task: PowerShell@2
  displayName: Pre initialization
  inputs:
      filePath: ./pre.ps1
      pwsh: true
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      LocalPublicNugetApiKey: $(LocalPublicNugetApiKey)
      GITHUB_API_TOKEN: $(GITHUB-API-TOKEN)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      # May possibly need these?
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOCLOUDSERVER: $(OCTOCLOUDSERVER)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)

- task: NuGetCommand@2
  displayName: 'Authenticate with NuGet feed'
  inputs:
    command: custom
    arguments: sources update -Name "PowerFarming Nuget" -Source "$(LocalNugetServerUrl)" -Username "$(LocalNugetUserName)" -Password "$(LocalNugetPassword)" -ConfigFile NuGet.Config -StorePasswordInClearText 

- task: PowerShell@2
  displayName: Initialization
  inputs:
      filePath: './build.dntool.ps1'
      arguments: '-target "Init" -InformationAction Continue -Verbosity $(Verbosity)'
      pwsh: true
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      LocalPublicNugetApiKey: $(LocalPublicNugetApiKey)
      GITHUB_API_TOKEN: $(GITHUB-API-TOKEN)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)
      CAKE_NUGET_USEINPROCESSCLIENT: true
      CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
      # Gitversion to build props
      JENKINS_HOME: "~/"

- task: PowerShell@2
  displayName: BuildPackagePublish
  inputs:
      filePath: './build.dntool.ps1'
      arguments: '-target "BuildPackagePublish" -InformationAction Continue -Verbosity $(Verbosity)'
      pwsh: true
  env:
      LocalNugetApiKey: $(LocalNugetApiKey)
      LocalNugetServerUrl: $(LocalNugetServerUrl)
      LocalNugetUserName: $(LocalNugetUserName)
      LocalNugetPassword: $(LocalNugetPassword)
      LocalPublicNugetApiKey: $(LocalPublicNugetApiKey)
      GITHUB_API_TOKEN: $(GITHUB-API-TOKEN)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      GITUSER: ""
      GITKEY: ""
      OCTOAPIKEY: $(OCTOAPIKEY)
      OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
      OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
      OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
      CAKE_NUGET_USEINPROCESSCLIENT: true
      CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
      # Gitversion to build props
      JENKINS_HOME: "~/"

# - task: PowerShell@2
#   displayName: Build
#   inputs:
#       filePath: './build.dntool.ps1'
#       arguments: '-target "Build" -Verbose -Verbosity $(Verbosity)'
#       pwsh: true
#   env:
#       LocalNugetApiKey: $(LocalNugetApiKey)
#       LocalNugetServerUrl: $(LocalNugetServerUrl)
#       LocalNugetUserName: $(LocalNugetUserName)
#       LocalNugetPassword: $(LocalNugetPassword)
#       GITHUB_PASSWORD: $(GITHUB-PASSWORD)
#       GITHUB_USERNAME: $(GITHUB-USERNAME)
#       GITUSER: ""
#       GITKEY: ""
#       OCTOAPIKEY: $(OCTOAPIKEY)
#       OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
#       OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
#       OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
#       CAKE_NUGET_USEINPROCESSCLIENT: true
#       CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
#       # Gitversion to build props
#       JENKINS_HOME: "~/"

# - powershell: .\build.dntool.ps1 -target "Test" -Verbosity $(Verbosity)
#   displayName: Test
#   env:
#       LocalNugetApiKey: $(LocalNugetApiKey)
#       LocalNugetServerUrl: $(LocalNugetServerUrl)
#       LocalNugetUserName: $(LocalNugetUserName)
#       LocalNugetPassword: $(LocalNugetPassword)
#       GITHUB_PASSWORD: $(GITHUB-PASSWORD)
#       GITHUB_USERNAME: $(GITHUB-USERNAME)
#       GITUSER: ""
#       GITKEY: ""
#       OCTOAPIKEY: $(OCTOAPIKEY)
#       OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
#       OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
#       OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
#       CAKE_NUGET_USEINPROCESSCLIENT: true
#       CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
#   enabled: false

# - powershell: .\build.dntool.ps1 -target "Package" -Verbosity $(Verbosity)
#   displayName: Package
#   env:
#       LocalNugetApiKey: $(LocalNugetApiKey)
#       LocalNugetServerUrl: $(LocalNugetServerUrl)
#       LocalNugetUserName: $(LocalNugetUserName)
#       LocalNugetPassword: $(LocalNugetPassword)
#       GITHUB_PASSWORD: $(GITHUB-PASSWORD)
#       GITHUB_USERNAME: $(GITHUB-USERNAME)
#       GITUSER: ""
#       GITKEY: ""
#       OCTOAPIKEY: $(OCTOAPIKEY)
#       OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
#       OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
#       OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
#       CAKE_NUGET_USEINPROCESSCLIENT: true
#       CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true

# - powershell: .\build.dntool.ps1 -target "Publish" -Verbosity $(Verbosity)
#   displayName: Publish
#   env:
#       LocalNugetApiKey: $(LocalNugetApiKey)
#       LocalNugetServerUrl: $(LocalNugetServerUrl)
#       LocalNugetUserName: $(LocalNugetUserName)
#       LocalNugetPassword: $(LocalNugetPassword)
#       GITHUB_PASSWORD: $(GITHUB-PASSWORD)
#       GITHUB_USERNAME: $(GITHUB-USERNAME)
#       GITUSER: ""
#       GITKEY: ""
#       OCTOAPIKEY: $(OCTOAPIKEY)
#       OCTOCLOUDAPIKEY: $(OCTOCLOUDAPIKEY)
#       OCTOPUS_CLI_API_KEY: $(OCTOPUS-CLI-APIKEY)
#       OCTOPUS_CLI_SERVER: $(OCTOPUS-CLI-SERVER)  
#       CAKE_NUGET_USEINPROCESSCLIENT: true
#       CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true

  # enabled: false

